services:
  client:
    image: client-dev
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api

  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server

  server:
    image: server-dev
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3003
      - DATABASE_URL=postgres://postgres:example@postgres:5432/blogapp
      - TEST_DATABASE_URL=postgres://postgres:example@postgres:5432/blogapp_test
      - NODE_ENV=development
      - SECRET=supersecret
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=blogapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d blogapp']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
